# Generated by Django 5.0.6 on 2024-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pradact',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='публичность'),
        ),
    ]
