# Generated by Django 5.0.6 on 2024-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pradact', '0002_pradact_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='pradact_images/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
